config/routes.rb
Devrails::Application.routes.draw do

  # get "eventbrite/index"

  devise_for :users

  match 'generate_judge_code', :to => 'judge_codes#generate_judge_code', :as => 'generate_judge_code', :via => [:get]
  match 'generate_competitor_position', :to => 'event_categories#generate_competitor_position', :as => 'generate_competitor_position', :via => [:get]
  match 'validate_judge_code', :to => 'judge_codes#validate_judge_code', :as => 'validate_judge_code', :via => [:get]
  match 'validate_app_user_by_email', :to => 'user#validate_app_user_by_email', :as => 'validate_app_user_by_email', :via => [:get]
  match 'populate_category_by_main_category', :to => 'categories#populate_category_by_main_category', :as => 'populate_category_by_main_category', :via => [:get]
  match 'populate_event_categories', :to => 'categories#populate_event_categories', :as => 'populate_event_categories', :via => [:get]
  match 'populate_user_not_participated_in_this_event', :to => 'events#populate_user_not_participated_in_this_event', :as => 'populate_user_not_participated_in_this_event', :via => [:get]
  match 'check_if_events', :to => 'events#check_if_events', :as => 'check_if_events', :via => [:get]
  match 'check_if_events_for_tabs', :to => 'events#check_if_events_for_tabs', :as => 'check_if_events_for_tabs', :via => [:get]
  match 'pull_event_registrants', :to => 'events#pull_event_registrants', :as => 'pull_event_registrants', :via => [:get]
  match 'participate_event_category', :to => 'events#participate_event_category', :as => 'participate_event_category', :via => [:post]
  match 'api/get_all_events_details', :to => 'events#get_all_events_details', :as => 'get_all_events_details', :via => [:get]
  match 'gcm_register', :to => 'user_reg_ids#gcm_register', :as => 'gcm_register', :via => [:post]
  match 'toggle_push_notification', :to => 'user_reg_ids#toggle_push_notification', :as => 'toggle_push_notification', :via => [:post]
  match 'get_states', :to => 'user#get_states', :as => 'get_states', :via => [:get]

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  namespace :admin do
      match 'take_photo', :to => 'event_category_registrations#take_photo', :as => 'take_photo', :via => [:get]
      match 'image_pop', :to => 'event_category_registrations#image_pop', :as => 'image_pop', :via => [:get]
      match 'update_photo', :to => 'event_category_registrations#update_photo', :as => 'update_photo', :via => [:put]
      match 'new_bulk_ck_mnrs', :to => 'admin_users#new_bulk_ck_mnrs', :as => 'new_bulk_ck_mnrs', :via => [:get]
      match 'save_bulk_ck_mnrs', :to => 'admin_users#save_bulk_ck_mnrs', :as => 'save_bulk_ck_mnrs', :via => [:post]
      match 'bulk_checkin_managers_onsubmit_validation', :to => 'admin_users#bulk_checkin_managers_onsubmit_validation', :as => 'bulk_checkin_managers_onsubmit_validation', :via => [:post]
      match 'select_event_photo', :to => 'events#select_event_photo', :as => 'select_event_photo', :via => [:get]
      match 'update_event_photo', :to => 'events#update_event_photo', :as => 'update_event_photo', :via => [:put]
      match 'select_event_clubs', :to => 'event_clubs#select_event_clubs', :as => 'select_event_clubs', :via => [:get]
      match 'update_event_clubs', :to => 'event_clubs#update_event_clubs', :as => 'update_event_clubs', :via => [:post]
      resource :event_category_registrations do
        member do
          put :update, :as => "update"
        end
      end
      resource :event_categories do
        member do
          put :update, :as => "update"
        end
      end
  end
  
  match 'user/sign_in' => 'user#sign_in'
  match 'user/sign_up' => 'user#sign_up'
  match 'user/create_non_profit_url' => 'user#create_non_profit_url'
  match 'user/delete_non_profit_url' => 'user#delete_non_profit_url'
  # match 'user/create_admin_push_notification' => 'user#create_admin_push_notification'
  # match 'user/delete_admin_push_notification' => 'user#delete_admin_push_notification'
  match '/populate_user_details' => 'user#populate_user_details', :via => [:get]
  match 'self_check_in' => 'events#self_check_in', :via => [:post]
  match 'forgot_password', :to => 'user#forgot_password', :as => 'forgot_password', :via => [:post]
  match 'validate_security_code', :to => 'user#validate_security_code', :as => 'validate_security_code', :via => [:post]
  match 'update_password_details', :to => 'user#update_password_details', :as => 'update_password_details', :via => [:post]
  match 'validate_number', :to => 'user#validate_number', :as => 'validate_number', :via => [:get]
  match 'generate_users_list', :to => 'user#generate_users_list', :as => 'generate_users_list', :via => [:get]
  match 'app_landing_page', :to => 'user#app_landing_page', :as => 'app_landing_page', :via => [:get]
  match '/get_competitor_details' => 'cards#get_competitor_details', :via => [:get]
  match '/my_card_details' => 'cards#my_card_details', :via => [:get]
  # match '/search_cards' => 'cards#search_cards', :via => [:get]
  match '/update_competitor_details' => 'cards#update_competitor_details', :via => [:post]
  match '/categories' => 'home#get_categories'
  match '/charities' => 'home#get_charities'
  match '/get_all_dropdown_values' => 'home#get_all_dropdown_values'
  match 'home' => 'home#index'
  match '/update_judge_code' => 'home#update_judge_code'
  match '/update_profile' => 'profiles#update_profile'
  match '/signup_clubs' => 'home#signup_clubs'
  match '/news' => 'home#news'
  # match '/eventbrite' => 'eventbrite#index'
  # match '/eventbrite/create_registration' => 'eventbrite#create_registration'
  match '/validate_email_on_create_new_user' => 'mobile_checkins#validate_email_on_create_new_user'
  match '/submit_tie_breaker' => 'event_categories#submit_tie_breaker', :via => [:post]
  # match 'motta_sathu', :to => 'events#motta_sathu', :as => 'motta_sathu', :via => [:get]
  # match '/delete_sathu' => 'event_categories#delete_sathu', :via => [:get]
  
  resources :cards
  resources :clubs
  resources :profiles
  resources :events do
    get 'results', :on => :member
    get 'photos', :on => :member
    get 'launch_event', :on => :member
    get 'event_stats', :on => :member
    get 'close_event', :on => :member
    get 'get_non_closed_event_category', :on => :member
    get 'load_more_judge_results_data', :on => :member
    get 'show_season_wise_donations', :on => :collection
  end
  resources :event_categories do
    post 'voting', :on => :member
    get 'announce_event_category_results', :on => :member
    get 'close_event_category', :on => :member
    get 'get_event_category_competitors', :on => :member
    get 'validate_category_name', :on => :member
    get 'force_close_judging_by_mc', :on => :member
    get 'fetch_tied_competitors', :on => :collection
  end

  resources :visitor_votes do
    collection do
      get 'load_visitor_votes'
    end
  end

  resources :judge_votes do
    member do
      get 'get_judges_votes'
    end
  end

  resources :event_fan_voting_results do
    collection do
      get 'track_overall_fan_voting_results'
      get 'track_category_fan_voting_results'
    end
  end

  resources :mobile_checkins do
    get 'event_checkin', :on => :member
    get 'take_photo', :to => 'mobile_checkins#take_photo', :as => 'take_photo'
    get 'search_users', :to => 'mobile_checkins#search_users', :as => 'search_users'
    get 'checkin_users', :to => 'mobile_checkins#checkin_users', :as => 'checkin_users'
    post 'update_checkin_users', :to => 'mobile_checkins#update_checkin_users', :as => 'update_checkin_users'
    post 'remove_checkin_users', :to => 'mobile_checkins#remove_checkin_users', :as => 'remove_checkin_users'
    put 'update_photo', :to => 'mobile_checkins#update_photo', :as => 'update_photo'
    put 'register_comp_to_events', :to => 'mobile_checkins#register_comp_to_events', :as => 'register_comp_to_events'
    get 'edit_checkedin_comp', :to => 'mobile_checkins#edit_checkedin_comp', :as => 'edit_checkedin_comp'
    put 'update_checkedin_comp', :to => 'mobile_checkins#update_checkedin_comp', :as => 'update_checkedin_comp'
    post 'create_new_competitor', :to => 'mobile_checkins#create_new_competitor', :as => 'create_new_competitor'
    delete 'delete_checkedin_comp', :to => 'mobile_checkins#delete_checkedin_comp', :as => 'delete_checkedin_comp'
    get 'delete_checkedin_competitor', :to => 'mobile_checkins#delete_checkedin_competitor', :as => 'delete_checkedin_competitor'
  end

  resources :event_requests do
    # get 'event_checkin', :on => :member    
    # put 'update_checkedin_comp', :to => 'mobile_checkins#update_checkedin_comp', :as => 'update_checkedin_comp'
    # post 'create', :to => 'event_requests#create', :as => 'create'
  end
  
   root :to => 'admin/dashboard#index'

end

app/models/mobile_checkin.rb
class MobileCheckin < ActiveRecord::Base
  # attr_accessible :title, :body
end

app/helpers/mobile_checkins_helper.rb
module MobileCheckinsHelper
end

app/views/mobile_checkins/_checkin_comps_partial.html.erb
<%if @registered_users.present?%>
    <%@registered_users.each do |registered_user|%>
        <div id="check_in_<%=registered_user.id%>" class="inner-article">
            <%if params[:is_removed].to_s!="true"%>
                <%=link_to "X", "#!", :onclick=>"fnQuickCheckInRemove(#{registered_user.id})", :class=> "btn-remove"%>
            <%end%>
            <h3><%=registered_user.number%>:&nbsp;&nbsp;<%=registered_user.user.try(:first_name).capitalize%> <%=registered_user.user.try(:last_name).capitalize%></h3>
            <p>
                <%if params[:is_checked_in] == "true" || !registered_user.try(:parent).present? || registered_user.try(:category).try(:name).present?%>
                    <%=registered_user.try(:category).try(:name)%>
                <%else%>
                    <%=registered_user.try(:parent).try(:category).try(:name)%>
                <%end%>
            </p> 
            <%=form_tag mobile_checkin_register_comp_to_events_path(@event), :name=> "register_member_form", :method => :put, :class => 'form-inline' do %>
                <%=hidden_field_tag 'event_id', @event.try(:id)%>
                <%=hidden_field_tag 'competitor_id', registered_user.user.try(:competitor).try(:id)%>
                <%unless params[:is_checked_in] == "true"%>
                    <div class="form-group">
                        <select class="form-control" name="category_id" id="category_id_<%=registered_user.try(:id)%>">
                            <option>Choose a Category</option>
                            <%@event_categories.each do |category|%>
                                <option value="<%=category.try(:id)%>"><%=category.try(:name)%></option>
                            <%end%>
                        </select>
                    </div>
                <%end%>
                <%if params[:is_checked_in].to_s!="true"%>
                    <%if registered_user.parent_id.present?%>
                        <input type="button" class="btn btn-primary" onclick="fnQuickCheckIn(<%=registered_user.id%>)" value="Check-In">
                    <%else%>
                    <%=submit_tag "Check-In", class: "btn btn-primary", :onclick=>"return validate_member_checkin_with_category($(this).parent().find('select').val());"%>
                    <%end%>
                <%else%>
                    <br/><br/>
                <%end%>
                <!-- <input type="button" class="btn btn-primary" onclick="fnQuickCheckInRemove(<%=registered_user.id%>)" value="Remove"> -->
            <%end%>
        </div>
    <%end%>
<%else%>
    <div class="inner-article">
        <h3 style="text-align:center;"> No Results Found </h3>
    </div>
<%end%>

app/views/mobile_checkins/checkin_users.html.erb
<section class="content-section">
    <h2><%=@event.try(:name).capitalize%></h2>
    <div class="panel">
        <article class="article article-style">
            <h4 class="title-style">Choose A Member</h4>
            <div id="replaceble_checkin_comps">
                <%= render partial: "checkin_comps_partial" %>
            </div>

        </article>
        <article class="article article-style">
            <div class="article-foot-btn form-group footAttr-link">
            <%#=link_to "Member Not In List", event_checkin_mobile_checkin_path(:id=>@event.id), :class=>"btn btn-primary"%>
            <%=link_to "Main List", mobile_checkin_checkin_users_path(:id=>@event.id,:is_checked_in=>false,:is_removed=>false), :class=>"tab_link_main_list"%>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
            <%=link_to "Checked-in Users", mobile_checkin_checkin_users_path(:id=>@event.id,:is_checked_in=>true,:is_removed=>false), :class=>"tab_link_checked_in_users"%>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
            <%=link_to "Removed Users", mobile_checkin_checkin_users_path(:id=>@event.id,:is_checked_in=>false,:is_removed=>true), :class=>"tab_link_removed_users"%>
            
            </div>
        </article><br><br>
    </div>
</section>
<style>
.current_tab{
    font-weight: bold;

}
</style>
<script>
// $(document).ready(function(){    
    var tab_type="";
    <%if params[:is_removed].to_s=="true"%>
    tab_type = "removed_users";
    <%elsif params[:is_checked_in].to_s=="true"%>
    tab_type = "checked_in_users"
    <%else%>
    tab_type = "main_list"
    <%end%> 
    $(".tab_link_"+tab_type).addClass("current_tab").click(function () {return false;});
// });
</script>

app/views/mobile_checkins/edit_checkedin_comp.html.erb
<script>
    function readURL(input,from_obj) {
        if (input.files && input.files[0]) {
            var reader = new FileReader();                  
            reader.onload = function (e) {
                $('#existing_image_id')
                .attr('src', e.target.result)
                
            };
            reader.readAsDataURL(input.files[0]);
        }
    }
</script>


<section class="content-section">
    <h2><%=@event.try(:name).capitalize%></h2>
    <div class="panel">
        <%#=form_tag mobile_checkin_update_checkedin_comp_path(@event), :name=> "edit_checkedin_comp_form", :method => :put, :class => 'position-form' do %>
        <%= form_for @evnt_cat_reg, :url=> mobile_checkin_update_checkedin_comp_path(@event), :name=> "edit_checkedin_comp_form", :method => :put, :class => 'position-form' do |f| -%>
            <article class="article article-style">
                <h4 class="title-style">Edit A User</h4>
                <%=hidden_field_tag 'user_id', @user.try(:id)%>
                <%=hidden_field_tag 'evnt_cat_reg_id', @evnt_cat_reg.try(:id)%>
                <%=hidden_field_tag 'event_id', @event.try(:id)%>
                <%=hidden_field_tag 'old_badge_id', @evnt_cat_reg.try(:number)%>
                <div class="form-group">
                    <%=text_field_tag 'first_name', @user.try(:first_name), :class=>"form-control", :placeholder=>"First Name"%>
                </div>
                <div class="form-group">
                    <%=text_field_tag 'last_name', @user.try(:last_name), :class=>"form-control", :placeholder=>"Last Name"%>
                </div> 
                <div class="form-group">
                    <%=select_tag "category", options_for_select(@event_categories.pluck(:name), @category.try(:name)), :class=>"form-control"%>
                </div> 
            </article>
            <article class="article article-style">
                <h4 class="title-style">Lanyard Number</h4>
                <div class="form-group">                    
                    <%#=text_field_tag 'badge_id', @evnt_cat_reg.try(:number), :class=>"form-control", :placeholder=>"000"%>
                    <input type="text" value="<%=@evnt_cat_reg.try(:number)%>" placeholder="000" name="badge_id" id="badge_id" class="form-control" onkeyup="this.value=this.value.replace(/[^\d]/,'')">
                </div> 
            </article>
            <article class="article article-style">
                <h4 class="title-style">Member Pic</h4>
                <figure class="upload-picture">
                    <!-- <img class="img-responsive" src="img/pictures.jpg" alt="" /> -->
                    <%unless @evnt_cat_reg.try(:event_photo_file_name).nil?%>
                        <%=image_tag ("#{AppConfig.s3_url}/attachments/#{@evnt_cat_reg.id}/original/"+@evnt_cat_reg.event_photo_file_name), :class=>"img-responsive", :id=>"existing_image_id"%>
                    <%end%>
                    <figcaption>
                        <div class="fileUpload">
                            <span ><img class="icon-camara" src="<%=AppConfig.image_domain%>/images/icon-camara.png" alt=""></span>
                            <%=f.file_field :event_photo, :class=>"upload", :onchange=>"if(validate_file_field($(this).attr('id'))) {readURL(this,'frm_chs_pt');}", :name=>"event_category_registration[event_photo]"%>
                        </div>
                    </figcaption>
                </figure>

                <div class="article-foot-btn text-center">
                    <%=link_to "Cancel", event_checkin_mobile_checkin_path(:id=>@event.id), :class=>"btn btn-primary"%>
                    <%=link_to "Delete", mobile_checkin_delete_checkedin_competitor_path(:evnt_cat_reg_id=>@evnt_cat_reg.id), :class=>"btn btn-primary btn-danger"%>
                    <%#=submit_tag "Submit", class: "btn btn-primary", :id=>"submit_id"%>
                    <button type="button" class="btn btn-primary" onclick="badge_id_onsubmit_validation($('#event_id').val(),$('#badge_id').val(),$('#old_badge_id').val(),$('#user_id').val())">Submit</button>
                </div>
            </article>
        <%end%>
    </div>
</section>

app/views/mobile_checkins/event_checkin.html.erb
<!--
<script type="text/javascript">
    setTimeout(function(){ fadeout_confirmation(); }, 5000);
</script>
-->

<div id ="confirmation_msg" class="alert alert-success clearfix" role="alert" style="<%if params[:success_msg]%>display:block;<%else%>display:none;<%end%>">
    <h3><span class="icon icon-success"></span>Confirmation</h3>
    <div>
        <p>Name: <span><%=@evnt_cat_reg.try(:user).try(:first_name)%> <%=@evnt_cat_reg.try(:user).try(:last_name)%></span></p>
        <p>Category: <span><%=@evnt_cat_reg.try(:category).try(:name)%></span></p>
        <p>Competitor ID: <span><%=@evnt_cat_reg.try(:number)%></span></p>
    </div>
</div>
<!-- /alert -->

<section class="content-section">
    <%class_name = (@event.try(:name).length >= 120) ? "extra-small" : (@event.try(:name).length >= 85) ? "small" : ""%>
    <h2 class="<%=class_name%>"><%=@event.try(:name).capitalize%></h2>
    <div class="panel">
        <!-- <form action=""> -->
        
        <article class="panel-header-btn">
            <%=link_to "Quick Check-In", mobile_checkin_checkin_users_path(@event.try(:id),:is_checked_in=>false,:is_removed=>false),:class=>"btn btn-primary"%>
        </article>
        <%=form_tag mobile_checkin_search_users_path(@event), :name=> "member_search_form", :method => :get, :class => 'position-form' do %>
            <article class="article">
                <h4>BBQL Member</h4>
                <div class="form-group">
                    <%=text_field_tag 'first_name', '', :class=>"form-control", :placeholder=>"First Name"%>
                </div>
                <div class="form-group">
                    <%=text_field_tag 'last_name', '', :class=>"form-control", :placeholder=>"Last Name"%>
                </div>
                <div class="article-foot-btn form-group">
                    <!-- <button type="button" class="btn btn-primary disabled">Scan</button> -->
                    <%=submit_tag "Search", class: "btn btn-primary", :onclick=>"return validate_member_search($('#first_name').val(),$('#last_name').val());"%>
                </div>
            </article>            
        <%end%>

        <%=form_tag mobile_checkin_create_new_competitor_path(@event), :name=> "create_competitor_form", :method => :post, :class => 'position-form', :id=> "create_competitor_form_id" do %>
            <article class="article">
                <h4>Create New Account</h4>
                <div class="form-group">
                    <%=text_field_tag 'create_first_name', '', :class=>"form-control", :placeholder=>"First Name"%>
                </div>
                <div class="form-group">
                    <%=text_field_tag 'create_last_name', '', :class=>"form-control", :placeholder=>"Last Name"%>
                </div>
                <div class="form-group">
                    <%=text_field_tag 'email', '', :class=>"form-control", :placeholder=>"Email Address"%>
                </div>
                <div class="form-group">
                    <select class="form-control" name="category_id" id="category_id">
                        <option>Category</option>                        
                        <%@event_categories.each do |category|%>
                            <option value="<%=category.try(:id)%>"><%=category.try(:name)%></option>
                        <%end%>
                    </select>
                </div>
                <div class="article-foot-btn form-group">
                    <%#=submit_tag "Submit", class: "btn btn-primary", :onclick=>"return validate_create_member($('#create_first_name').val(),$('#create_last_name').val(),$('#email').val(),$('#category_id').val());"%>

                    <input type="button" value="Submit" onclick="return validate_create_member($('#create_first_name').val(),$('#create_last_name').val(),$('#email').val(),$('#category_id').val());" name="commit" class="btn btn-primary">

                </div>
            </article>
        <%end%>

        <%=form_tag mobile_checkin_take_photo_path(@event), :name=> "registered_member_form", :method => :get, :class => 'position-form' do %>
            <article class="article">
                <h4><span style="color:red;"><%=@registered_competitors.try(:count)%></span> Pre-Registered Members</h4>
                <div class="form-group">
                    <select class="form-control" name="evnt_cat_reg_id" id="evnt_cat_reg_id">
                        <option>Choose A Member</option>
                        <%@registered_competitors.each do |reg_comp|%>
                            <option value=<%=reg_comp.id%>>
                                <%=reg_comp.try(:user).try(:last_name).try(:capitalize)%><%=reg_comp.try(:user).try(:last_name).present? ? "," : ""%> <%=reg_comp.try(:user).try(:first_name)%>
                            </option>
                        <%end%>
                    </select>
                </div>
                <div class="article-foot-btn form-group">
                    <!-- <button type="button" class="btn btn-primary disabled">Scan</button> -->
                    <%=submit_tag "Check-In", class: "btn btn-primary", :onclick=>"return validate_member_checkin($('#evnt_cat_reg_id').val());"%>
                </div>
            </article>
        <%end%>

            <%=form_tag mobile_checkin_edit_checkedin_comp_path(@event), :name=> "edit_checkedin_comp_form", :method => :get, :class => 'position-form' do %>
                <article class="article">
                    <h4>Edit Checked-In Member</h4>
                    <div class="form-group">
                        <select class="form-control" name="selected_user_id" id="selected_user_id">
                            <option>Choose A Checked-In Member</option>
                            <%@checkedin_competitors.each do |checkedin_comp|%>
                                <option value=<%=checkedin_comp.try(:user).try(:id)%>>
                                    <%=checkedin_comp.try(:user).try(:last_name).try(:capitalize)%><%=checkedin_comp.try(:user).try(:last_name).present? ? "," : ""%> <%=checkedin_comp.try(:user).try(:first_name)%>
                                </option>
                            <%end%>
                        </select>
                    </div>
                    <div class="article-foot-btn form-group">
                        <%=submit_tag "Edit", class: "btn btn-primary", :onclick=>"return validate_edit_member($('#selected_user_id').val());"%>
                    </div>
                </article>
            <%end%>

            <!-- <%#=form_tag mobile_checkin_delete_checkedin_comp_path(@event), :name=> "delete_checkedin_comp_form", :method => :delete, :class => 'position-form' do %>
                <article class="article">
                    <h4>Delete Checked-In Members</h4>
                    <div class="form-group checkboxes">
                        <%#@checkedin_competitors.each do |checkedin_comp|%>
                            <%#= check_box_tag "checkedin_comp[]", checkedin_comp.try(:user).try(:id) -%> <%#=checkedin_comp.try(:user).try(:last_name).try(:capitalize)%><%#=checkedin_comp.try(:user).try(:last_name).present? ? "," : ""%> <%#=checkedin_comp.try(:user).try(:first_name)%> <br/>
                        <%#end%>
                    </div>
                    <div class="article-foot-btn form-group">
                        <%#=submit_tag "Delete", class: "btn btn-primary", :onclick=>"return validate_delete_members($('.checkboxes').find('input:checked'));"%>
                    </div>
                </article> -->
            <%#end%>

        <!-- </form> -->
    </div>
</section>
<!-- /content-section --> 

app/views/mobile_checkins/index.html.erb
<section class="content-section">
    <h2>All Events</h2>
    <div class="panel events-list">
        <form action="">
            <article class="article">
                <h4>Live Events</h4>
                <div class="form-group">
                    <%live_events = @events.present? ? @events.where(:status=>"OnGoing") : []%>
                    <%if live_events.present?%>
                        <%live_events.each_with_index do |event,index|%>
                            <%=link_to event.name, event_checkin_mobile_checkin_path(event.id)%>
                        <%end%>
                    <%else%>
                        <div style="text-align:center;">No Live Events Found</div>
                    <%end%>
                </div>                
            </article>
            <article class="article">
                <h4>Upcoming Events</h4>
                <div class="form-group">
                    <%upcoming_events = @events.present? ? @events.where(:status=>"Upcoming") : []%>
                    <%if upcoming_events.present?%>
                        <%upcoming_events.each_with_index do |event,index|%>
                            <%=link_to event.name, event_checkin_mobile_checkin_path(event.id)%>
                        <%end%>
                    <%else%>
                        <div style="text-align:center;">No Upcoming Events Found</div>
                    <%end%>
                </div>                
            </article>
        </form>
    </div>
</section>
<!-- /content-section -->

app/views/mobile_checkins/search_users.html.erb
<section class="content-section">
    <h2><%=@event.try(:name).capitalize%></h2>
    <div class="panel">
        <article class="article article-style">
            <h4 class="title-style">Choose A Member</h4>
            <%if @all_users.present?%>
                <%@all_users.each do |user|%>
                    <div class="inner-article">
                        <h3><%=user.try(:first_name).capitalize%> <%=user.try(:last_name).capitalize%></h3>
                        <p><%=user.try(:email)%></p> 
                        <%=form_tag mobile_checkin_register_comp_to_events_path(@event), :name=> "register_member_form", :method => :put, :class => 'form-inline' do %>
                            <%=hidden_field_tag 'event_id', @event.try(:id)%>
                            <%=hidden_field_tag 'competitor_id', user.try(:competitor).try(:id)%>
                            <div class="form-group">
                                <select class="form-control" name="category_id" id="category_id_<%=user.try(:id)%>">
                                    <option>Choose a Category</option>
                                    <%@event_categories.each do |category|%>
                                        <option value="<%=category.try(:id)%>"><%=category.try(:name)%></option>
                                    <%end%>
                                </select>
                            </div>
                            <%=submit_tag "Check-In", class: "btn btn-primary", :onclick=>"return validate_member_checkin_with_category($(this).parent().find('select').val());"%>
                        <%end%>
                    </div>
                <%end%>
            <%else%>
                <div class="inner-article">
                    <h3 style="text-align:center;"> No Results Found </h3>
                </div>
            <%end%>

        </article>
        <article class="article article-style">
            <div class="article-foot-btn form-group">
            <%=link_to "Member Not In List", event_checkin_mobile_checkin_path(:id=>@event.id), :class=>"btn btn-primary"%>
            </div>
        </article><br><br>
    </div>
</section>