config/routes.rb
Devrails::Application.routes.draw do

  # get "eventbrite/index"

  devise_for :users

  match 'generate_judge_code', :to => 'judge_codes#generate_judge_code', :as => 'generate_judge_code', :via => [:get]
  match 'generate_competitor_position', :to => 'event_categories#generate_competitor_position', :as => 'generate_competitor_position', :via => [:get]
  match 'validate_judge_code', :to => 'judge_codes#validate_judge_code', :as => 'validate_judge_code', :via => [:get]
  match 'validate_app_user_by_email', :to => 'user#validate_app_user_by_email', :as => 'validate_app_user_by_email', :via => [:get]
  match 'populate_category_by_main_category', :to => 'categories#populate_category_by_main_category', :as => 'populate_category_by_main_category', :via => [:get]
  match 'populate_event_categories', :to => 'categories#populate_event_categories', :as => 'populate_event_categories', :via => [:get]
  match 'populate_user_not_participated_in_this_event', :to => 'events#populate_user_not_participated_in_this_event', :as => 'populate_user_not_participated_in_this_event', :via => [:get]
  match 'check_if_events', :to => 'events#check_if_events', :as => 'check_if_events', :via => [:get]
  match 'check_if_events_for_tabs', :to => 'events#check_if_events_for_tabs', :as => 'check_if_events_for_tabs', :via => [:get]
  match 'pull_event_registrants', :to => 'events#pull_event_registrants', :as => 'pull_event_registrants', :via => [:get]
  match 'participate_event_category', :to => 'events#participate_event_category', :as => 'participate_event_category', :via => [:post]
  match 'api/get_all_events_details', :to => 'events#get_all_events_details', :as => 'get_all_events_details', :via => [:get]
  match 'gcm_register', :to => 'user_reg_ids#gcm_register', :as => 'gcm_register', :via => [:post]
  match 'toggle_push_notification', :to => 'user_reg_ids#toggle_push_notification', :as => 'toggle_push_notification', :via => [:post]
  match 'get_states', :to => 'user#get_states', :as => 'get_states', :via => [:get]

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  namespace :admin do
      match 'take_photo', :to => 'event_category_registrations#take_photo', :as => 'take_photo', :via => [:get]
      match 'image_pop', :to => 'event_category_registrations#image_pop', :as => 'image_pop', :via => [:get]
      match 'update_photo', :to => 'event_category_registrations#update_photo', :as => 'update_photo', :via => [:put]
      match 'new_bulk_ck_mnrs', :to => 'admin_users#new_bulk_ck_mnrs', :as => 'new_bulk_ck_mnrs', :via => [:get]
      match 'save_bulk_ck_mnrs', :to => 'admin_users#save_bulk_ck_mnrs', :as => 'save_bulk_ck_mnrs', :via => [:post]
      match 'bulk_checkin_managers_onsubmit_validation', :to => 'admin_users#bulk_checkin_managers_onsubmit_validation', :as => 'bulk_checkin_managers_onsubmit_validation', :via => [:post]
      match 'select_event_photo', :to => 'events#select_event_photo', :as => 'select_event_photo', :via => [:get]
      match 'update_event_photo', :to => 'events#update_event_photo', :as => 'update_event_photo', :via => [:put]
      match 'select_event_clubs', :to => 'event_clubs#select_event_clubs', :as => 'select_event_clubs', :via => [:get]
      match 'update_event_clubs', :to => 'event_clubs#update_event_clubs', :as => 'update_event_clubs', :via => [:post]
      resource :event_category_registrations do
        member do
          put :update, :as => "update"
        end
      end
      resource :event_categories do
        member do
          put :update, :as => "update"
        end
      end
  end
  
  match 'user/sign_in' => 'user#sign_in'
  match 'user/sign_up' => 'user#sign_up'
  match 'user/create_non_profit_url' => 'user#create_non_profit_url'
  match 'user/delete_non_profit_url' => 'user#delete_non_profit_url'
  # match 'user/create_admin_push_notification' => 'user#create_admin_push_notification'
  # match 'user/delete_admin_push_notification' => 'user#delete_admin_push_notification'
  match '/populate_user_details' => 'user#populate_user_details', :via => [:get]
  match 'self_check_in' => 'events#self_check_in', :via => [:post]
  match 'forgot_password', :to => 'user#forgot_password', :as => 'forgot_password', :via => [:post]
  match 'validate_security_code', :to => 'user#validate_security_code', :as => 'validate_security_code', :via => [:post]
  match 'update_password_details', :to => 'user#update_password_details', :as => 'update_password_details', :via => [:post]
  match 'validate_number', :to => 'user#validate_number', :as => 'validate_number', :via => [:get]
  match 'generate_users_list', :to => 'user#generate_users_list', :as => 'generate_users_list', :via => [:get]
  match 'app_landing_page', :to => 'user#app_landing_page', :as => 'app_landing_page', :via => [:get]
  match '/get_competitor_details' => 'cards#get_competitor_details', :via => [:get]
  match '/my_card_details' => 'cards#my_card_details', :via => [:get]
  # match '/search_cards' => 'cards#search_cards', :via => [:get]
  match '/update_competitor_details' => 'cards#update_competitor_details', :via => [:post]
  match '/categories' => 'home#get_categories'
  match '/charities' => 'home#get_charities'
  match '/get_all_dropdown_values' => 'home#get_all_dropdown_values'
  match 'home' => 'home#index'
  match '/update_judge_code' => 'home#update_judge_code'
  match '/update_profile' => 'profiles#update_profile'
  match '/signup_clubs' => 'home#signup_clubs'
  match '/news' => 'home#news'
  # match '/eventbrite' => 'eventbrite#index'
  # match '/eventbrite/create_registration' => 'eventbrite#create_registration'
  match '/validate_email_on_create_new_user' => 'mobile_checkins#validate_email_on_create_new_user'
  match '/submit_tie_breaker' => 'event_categories#submit_tie_breaker', :via => [:post]
  # match 'motta_sathu', :to => 'events#motta_sathu', :as => 'motta_sathu', :via => [:get]
  # match '/delete_sathu' => 'event_categories#delete_sathu', :via => [:get]
  
  resources :cards
  resources :clubs
  resources :profiles
  resources :events do
    get 'results', :on => :member
    get 'photos', :on => :member
    get 'launch_event', :on => :member
    get 'event_stats', :on => :member
    get 'close_event', :on => :member
    get 'get_non_closed_event_category', :on => :member
    get 'load_more_judge_results_data', :on => :member
    get 'show_season_wise_donations', :on => :collection
  end
  resources :event_categories do
    post 'voting', :on => :member
    get 'announce_event_category_results', :on => :member
    get 'close_event_category', :on => :member
    get 'get_event_category_competitors', :on => :member
    get 'validate_category_name', :on => :member
    get 'force_close_judging_by_mc', :on => :member
    get 'fetch_tied_competitors', :on => :collection
  end

  resources :visitor_votes do
    collection do
      get 'load_visitor_votes'
    end
  end

  resources :judge_votes do
    member do
      get 'get_judges_votes'
    end
  end

  resources :event_fan_voting_results do
    collection do
      get 'track_overall_fan_voting_results'
      get 'track_category_fan_voting_results'
    end
  end

  resources :mobile_checkins do
    get 'event_checkin', :on => :member
    get 'take_photo', :to => 'mobile_checkins#take_photo', :as => 'take_photo'
    get 'search_users', :to => 'mobile_checkins#search_users', :as => 'search_users'
    get 'checkin_users', :to => 'mobile_checkins#checkin_users', :as => 'checkin_users'
    post 'update_checkin_users', :to => 'mobile_checkins#update_checkin_users', :as => 'update_checkin_users'
    post 'remove_checkin_users', :to => 'mobile_checkins#remove_checkin_users', :as => 'remove_checkin_users'
    put 'update_photo', :to => 'mobile_checkins#update_photo', :as => 'update_photo'
    put 'register_comp_to_events', :to => 'mobile_checkins#register_comp_to_events', :as => 'register_comp_to_events'
    get 'edit_checkedin_comp', :to => 'mobile_checkins#edit_checkedin_comp', :as => 'edit_checkedin_comp'
    put 'update_checkedin_comp', :to => 'mobile_checkins#update_checkedin_comp', :as => 'update_checkedin_comp'
    post 'create_new_competitor', :to => 'mobile_checkins#create_new_competitor', :as => 'create_new_competitor'
    delete 'delete_checkedin_comp', :to => 'mobile_checkins#delete_checkedin_comp', :as => 'delete_checkedin_comp'
    get 'delete_checkedin_competitor', :to => 'mobile_checkins#delete_checkedin_competitor', :as => 'delete_checkedin_competitor'
  end

  resources :event_requests do
    # get 'event_checkin', :on => :member    
    # put 'update_checkedin_comp', :to => 'mobile_checkins#update_checkedin_comp', :as => 'update_checkedin_comp'
    # post 'create', :to => 'event_requests#create', :as => 'create'
  end
  
   root :to => 'admin/dashboard#index'

end

app/models/event_fan_voting_result.rb
class EventFanVotingResult < ActiveRecord::Base
  # attr_accessible :title, :body

  def self.track_category_fan_voting_results(event_id,category_id)
    event_category = EventCategory.where(:event_id=>event_id,:category_id=>category_id).includes(:visitor_votes).first
    avg_jud_res = EventCompetitorResult.where(:event_category_id=>event_category.try(:id), :avg_visitor_results => 0).order(:position).limit(3) # To fetch top 3 competiors based on position (rank)
    hash = self.do_calculations(avg_jud_res,event_category) if avg_jud_res.present? && event_category.present?
    return hash
  end

  def self.track_individual_scores(event_id,category_id,user_id)
    event_category = EventCategory.includes(:visitor_votes).where(:event_id=>event_id,:category_id=>category_id).try(:first)
    avg_jud_res = event_category.event_competitor_results.where(:avg_visitor_results => 0).order(:position).limit(3)
    first = second = third = nil
    avg_jud_res.each_with_index do |result,index|
      visi_votes_1 = event_category.visitor_votes.find_all{|vote| vote.position1==result.event_competitor_id and vote.user_id == user_id}
      visi_votes_2 = event_category.visitor_votes.find_all{|vote| vote.position2==result.event_competitor_id and vote.user_id == user_id}
      visi_votes_3 = event_category.visitor_votes.find_all{|vote| vote.position3==result.event_competitor_id and vote.user_id == user_id}
      if (index == 0)
        first, second, third = self.get_three_positions(visi_votes_1,visi_votes_2,visi_votes_3,10,7,3,first,second,third)
      elsif (index == 1)
        first, second, third = self.get_three_positions(visi_votes_1,visi_votes_2,visi_votes_3,6,9,5,first,second,third)
      else
        first, second, third = self.get_three_positions(visi_votes_1,visi_votes_2,visi_votes_3,2,4,8,first,second,third)
      end
    end
    return first, second, third
  end

  def self.get_three_positions(visi_votes_1,visi_votes_2,visi_votes_3,one,two,three,first,second,third)
    first = visi_votes_1.present? ? one : first
    second = visi_votes_2.present? ? two : second
    third = visi_votes_3.present? ? three : third
    return first, second, third
  end

  def self.do_calculations(avg_jud_res,event_category)
    arr = []
    hash = {}
    avg_jud_res.each_with_index do |result,index|
      visi_votes_1 = event_category.visitor_votes.find_all{|vote| vote.position1==result.event_competitor_id}.collect(&:user_id)
      visi_votes_2 = event_category.visitor_votes.find_all{|vote| vote.position2==result.event_competitor_id}.collect(&:user_id)
      visi_votes_3 = event_category.visitor_votes.find_all{|vote| vote.position3==result.event_competitor_id}.collect(&:user_id)
      visi_votes_4 = event_category.visitor_votes.find_all{|vote| (vote.position1 != result.event_competitor_id && vote.position2 != result.event_competitor_id && vote.position3 != result.event_competitor_id)}.collect(&:user_id) # To get the fans who have not event match a single judge pick and they will be awarded 0 points
      if (index == 0)
        self.push_hash_arr(arr,visi_votes_1,10)
        self.push_hash_arr(arr,visi_votes_2,7)
        self.push_hash_arr(arr,visi_votes_3,3)
      elsif (index == 1)
        self.push_hash_arr(arr,visi_votes_1,6)
        self.push_hash_arr(arr,visi_votes_2,9)
        self.push_hash_arr(arr,visi_votes_3,5)
      else
        self.push_hash_arr(arr,visi_votes_1,2)
        self.push_hash_arr(arr,visi_votes_2,4)
        self.push_hash_arr(arr,visi_votes_3,8)
      end
      self.push_hash_arr(arr,visi_votes_4,0)
    end    
    hash = arr.compact.inject{|key, val| key.merge( val ){|k, old_v, new_v| old_v + new_v}} if arr.present?
    hash = Hash[hash.sort_by{|k, v| v}.reverse] if hash.present?
    return hash
  end

  def self.push_hash_arr(arr,visi_votes,value)
    visi_votes.each do |visi|
      arr.push({visi=>value})
    end
  end

  def self.track_overall_fan_voting_results(event_id)
    event = Event.find(event_id)
    event_categories = EventCategory.where(:event_id=>event_id) unless event_id.nil?
    main_arr = []
    main_hash = {}
    event_categories.includes(:event_competitor_results,:visitor_votes=>:user).each do |event_category|
      avg_jud_res = event_category.event_competitor_results.where(:avg_visitor_results => 0).order(:position).limit(3) #EventCompetitorResult.where(:event_category_id=>event_category.try(:id), :avg_visitor_results => 0).order(:position).limit(3) # To fetch top 3 competiors based on position (rank)
      hash = self.do_calculations(avg_jud_res,event_category) if avg_jud_res.present?
      main_arr.push(hash)
    end if event_categories.present?
    main_hash = main_arr.compact.inject{|memo, el| memo.merge( el ){|k, old_v, new_v| old_v + new_v}} if main_arr.present?
    main_hash = Hash[main_hash.sort_by{|k, v| v}.reverse] if main_hash.present?
    return main_hash
  end

	def self.to_csv(main_hash)
		CSV.generate do |csv|
        csv << ["Rank", "First Name", "Last Name", "Email", "Fan Score"] ## Header values of CSV
        main_hash.each_with_index do |hash,index|
          user = User.find_by_id(hash[0])                
          csv << [index + 1, user.try(:first_name).try(:capitalize), user.try(:last_name).try(:capitalize), user.try(:email), hash[1]] ##Row values of CSV
        end
      end
  end
end

app/controllers/event_fan_voting_results_controller.rb
class EventFanVotingResultsController < ApplicationController
	require 'csv'
	before_filter :check_user_by_uuid, :only => [:track_FFH_results]
	def track_category_fan_voting_results
		hash = EventFanVotingResult.track_category_fan_voting_results(params[:event_id],params[:category_id])
		if params[:csv_param]
    		respond_to do |format|
    		   format.html
    		   format.csv { send_data EventFanVotingResult.to_csv(hash), :filename => 'Event Category Fan Voting Results.csv' }
    		end
		else
			@users = User.where(:id=>hash.try(:keys))
			# render :json => { :resultsPartial => render_to_string('event_fan_voting_results/_fan_voting_results', :layout => false, :locals => { :hash => hash, :event_id=>params[:event_id], :category=>event_category.try(:category)}), :sidebarPartial => render_to_string('event_fan_voting_results/_sidebar_filters', :layout => false)}
			render :json => { :resultsPartial => render_to_string('event_fan_voting_results/_fan_voting_results', :layout => false, :locals => { :hash => hash, :event_id=>params[:event_id], :category_id=>params[:category_id]})}
		end
	end

	def do_calculations(avg_jud_res,event_category)
		hash = EventFanVotingResult.do_calculations(avg_jud_res,event_category)
		return hash
	end

	def track_overall_fan_voting_results
		main_hash = EventFanVotingResult.track_overall_fan_voting_results(params[:event_id])

		@users = User.where(:id=>main_hash.try(:keys))		
		if params[:csv_param]
    		respond_to do |format|
    		   format.html
    		   format.csv { send_data EventFanVotingResult.to_csv(main_hash), :filename => 'Event Overall Fan Voting Results.csv' }
    		end
		else        
			# render :json => { :resultsPartial => render_to_string('event_fan_voting_results/_fan_voting_results', :layout => false, :locals => { :hash => main_hash, :event_id=>params[:event_id], :category=>nil}), :sidebarPartial => render_to_string('event_fan_voting_results/_sidebar_filters', :layout => false)}
			render :json => { :resultsPartial => render_to_string('event_fan_voting_results/_fan_voting_results', :layout => false, :locals => { :hash => main_hash, :event_id=>params[:event_id], :category_id=>nil})}
		end
	end
end

app/helpers/event_fan_voting_results_helper.rb
module EventFanVotingResultsHelper
end

app/views/event_fan_voting_results/_fan_voting_results.html.erb
<script type="text/javascript">
  var event_id = $("#page_title").text().split(">")[1];
</script>
<div class="buttons" style="float:left; margin:0 0 20px 0">
  <input type="submit" value="Overall Results" name="commit" style="cursor:pointer;" onclick = "track_overall_fan_voting_results(event_id);">      
</div>

<div class="buttons">
  <%categories = Event.find_by_id(event_id).categories.joins(:event_categories).uniq.order('event_categories.sort_order IS NULL, event_categories.sort_order ASC')%>
  <%=select_tag :event_category, options_from_collection_for_select(categories, :id, :name, category_id), :prompt => "View Results by Category",:class=>"event-category-dropdown", :onchange => "track_category_fan_voting_results(event_id,$(this).find(':selected').val());"%>
</div>

<table id="index_table_event_fan_voting_results" class="index_table index tablesorter" cellspacing="0" cellpadding="0" border="border" width="100%" paginator="true">
<thead style="cursor:pointer;">
<tr>
  <th class="sortable col">Rank</td>
  <th class="sortable col">Fan Score</td>
  <th class="sortable col">First Name</td>
  <th class="sortable col">Last Name</td>
  <th class="sortable col">Email</td>  
</tr>
</thead>
<tbody>
  <%if hash.present?%>
    <%current_max=hash.first[1]%>
    <%current_rank=1%>
    <%hash.each_with_index do |hsh,index|%>
      <% 
        user = @users.find_all{|user| user.id==hsh[0]}.first
      %>
      <%if hsh[1] < current_max
        current_rank = index+1
        current_max=hsh[1]      
      end%>
      <tr id = "fan_vote_<%=index+1%>" class= "<%=((index+1)%2 == 0) ? 'even' : 'odd' %>">
        <td class="col"><%=current_rank%></td>
        <td class="col"><%=hsh[1]%></td>
        <td class="col"><%=user.try(:first_name).try(:capitalize)%></td>
        <td class="col"><%=user.try(:last_name).try(:capitalize)%></td>
        <td class="col"><%=user.try(:email)%></td>        
      </tr>
    <%end%>
  <%else%>
    <tr>
      <td class="col" colspan="5" style="text-align:center;background: #FFF">No Result found</td>
    </tr>
  <%end%>
</tbody>
</table>

<div style="float:left">
  <%if category_id.present?%>
    Download: <%= link_to "CSV", track_category_fan_voting_results_event_fan_voting_results_path(format: "csv", csv_param: true, event_id: event_id, category_id: category_id) %>
  <%else%>
    Download: <%= link_to "CSV", track_overall_fan_voting_results_event_fan_voting_results_path(format: "csv", csv_param: true, event_id: event_id) %>
  <%end%>
</div>


<script type="text/javascript">
$(document).ready(function()
    { 
        $("#index_table_event_fan_voting_results").tablesorter();
        // Need to modify, because dropdown is not working fine.
        customSelectbox();
        function customSelectbox() {
          // Iterate over each select element
          $('.customSelect').each(function () {

              // Cache the number of options
              var $this = $(this),
                  numberOfOptions = $(this).children('option').length;

              // Hides the select element
              $this.addClass('s-hidden');

              // Wrap the select element in a div
              $this.wrap('<div class="select-box"></div>');

              // Insert a styled div to sit over the top of the hidden select element
              $this.after('<div class="styledSelect"></div>');

              // Cache the styled div
              var $styledSelect = $this.next('div.styledSelect');

              // Show the first select option in the styled div
              $styledSelect.text($this.children('option').eq(0).text());

              // Insert an unordered list after the styled div and also cache the list
              var $list = $('<ul />', {
                  'class': 'options'
              }).insertAfter($styledSelect);

              // Insert a list item into the unordered list for each select option
              for (var i = 0; i < numberOfOptions; i++) {
                  $('<li />', {
                      text: $this.children('option').eq(i).text(),
                      rel: $this.children('option').eq(i).val()
                  }).appendTo($list);
              }

              // Cache the list items
              var $listItems = $list.children('li');

              // Show the unordered list when the styled div is clicked (also hides it if the div is clicked again)
              $styledSelect.click(function (e) {
                  e.stopPropagation();
                  $('div.styledSelect.active').each(function () {
                      $(this).removeClass('active').next('ul.options').hide();
                  });
                  $(this).toggleClass('active').next('ul.options').toggle();
              });

              // Hides the unordered list when a list item is clicked and updates the styled div to show the selected list item
              // Updates the select element to have the value of the equivalent option
              $listItems.click(function (e) {
                  e.stopPropagation();
                  $styledSelect.text($(this).text()).removeClass('active');
                  $this.val($(this).attr('rel'));
                  $list.hide();
                  /* alert($this.val()); Uncomment this for demonstration! */
              });

              // Hides the unordered list when clicking outside of it
              $(document).click(function () {
                  $styledSelect.removeClass('active');
                  $list.hide();
              });

          });
      }

    }
);
</script>

app/views/event_fan_voting_results/_sidebar_filters.html.erb
<div id="filters_sidebar_section" class="sidebar_section panel">
	<h3>Filters</h3>
	<div class="panel_contents">
		<%#= form_tag load_reports_games_statistics_path, :method => 'get', remote: true, :id=>"new_q", :class=>"filter_form" do %>
			<div style="margin:0;padding:0;display:inline">
				
			</div>

			<div class="filter_form_field filter_date_range">
				<label for="q_game_date_gteq" class="label">Game Date</label>
				<input type="text" value="" size="12" name="q[game_date_gteq]" max="10" id="q_game_date_gteq" class="datepicker">
				<span class="seperator">-</span>
				<input type="text" value="" size="12" name="q[game_date_lteq]" max="10" id="q_game_date_lteq" class="datepicker">
			</div>
			<div class="filter_form_field filter_select">
				<label for="h_contest_id" class="label">Contest</label>
				<select name="h[contest_id_eq]" id="h_contest_id">
					<option value="">Any</option>
					<%#=contests.each do |contest|%>
						<option value="<%#=contest.id%>"><%#=contest.name%></option>
					<%#end%>					
				</select>
			</div>
			<div class="filter_form_field filter_select">
				<label for="g_product_id" class="label">Product Name</label>
				<select name="g[product_id_eq]" id="g_product_id">
					<option value="">Any</option>					
					<%#=products.each do |product|%>
						<option value="<%#=product.id%>"><%#=product.name%></option>
					<%#end%>
				</select>
			</div>

			<div class="buttons">
				<input type="button" class="button-css" value="Filter" name="commit" onclick="load_reports('false');">
				<a class="clear_filters_btn" href="#" onclick="$('#new_q')[0].reset();load_reports();">Clear Filters</a>
				<input type="hidden" value="id_desc" name="order" id="hidden_active_admin_order">
			</div>
		<%#end%>
	</div>
</div>	