config/routes.rb
Devrails::Application.routes.draw do

  # get "eventbrite/index"

  devise_for :users

  match 'generate_judge_code', :to => 'judge_codes#generate_judge_code', :as => 'generate_judge_code', :via => [:get]
  match 'generate_competitor_position', :to => 'event_categories#generate_competitor_position', :as => 'generate_competitor_position', :via => [:get]
  match 'validate_judge_code', :to => 'judge_codes#validate_judge_code', :as => 'validate_judge_code', :via => [:get]
  match 'validate_app_user_by_email', :to => 'user#validate_app_user_by_email', :as => 'validate_app_user_by_email', :via => [:get]
  match 'populate_category_by_main_category', :to => 'categories#populate_category_by_main_category', :as => 'populate_category_by_main_category', :via => [:get]
  match 'populate_event_categories', :to => 'categories#populate_event_categories', :as => 'populate_event_categories', :via => [:get]
  match 'populate_user_not_participated_in_this_event', :to => 'events#populate_user_not_participated_in_this_event', :as => 'populate_user_not_participated_in_this_event', :via => [:get]
  match 'check_if_events', :to => 'events#check_if_events', :as => 'check_if_events', :via => [:get]
  match 'check_if_events_for_tabs', :to => 'events#check_if_events_for_tabs', :as => 'check_if_events_for_tabs', :via => [:get]
  match 'pull_event_registrants', :to => 'events#pull_event_registrants', :as => 'pull_event_registrants', :via => [:get]
  match 'participate_event_category', :to => 'events#participate_event_category', :as => 'participate_event_category', :via => [:post]
  match 'api/get_all_events_details', :to => 'events#get_all_events_details', :as => 'get_all_events_details', :via => [:get]
  match 'gcm_register', :to => 'user_reg_ids#gcm_register', :as => 'gcm_register', :via => [:post]
  match 'toggle_push_notification', :to => 'user_reg_ids#toggle_push_notification', :as => 'toggle_push_notification', :via => [:post]
  match 'get_states', :to => 'user#get_states', :as => 'get_states', :via => [:get]

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  namespace :admin do
      match 'take_photo', :to => 'event_category_registrations#take_photo', :as => 'take_photo', :via => [:get]
      match 'image_pop', :to => 'event_category_registrations#image_pop', :as => 'image_pop', :via => [:get]
      match 'update_photo', :to => 'event_category_registrations#update_photo', :as => 'update_photo', :via => [:put]
      match 'new_bulk_ck_mnrs', :to => 'admin_users#new_bulk_ck_mnrs', :as => 'new_bulk_ck_mnrs', :via => [:get]
      match 'save_bulk_ck_mnrs', :to => 'admin_users#save_bulk_ck_mnrs', :as => 'save_bulk_ck_mnrs', :via => [:post]
      match 'bulk_checkin_managers_onsubmit_validation', :to => 'admin_users#bulk_checkin_managers_onsubmit_validation', :as => 'bulk_checkin_managers_onsubmit_validation', :via => [:post]
      match 'select_event_photo', :to => 'events#select_event_photo', :as => 'select_event_photo', :via => [:get]
      match 'update_event_photo', :to => 'events#update_event_photo', :as => 'update_event_photo', :via => [:put]
      match 'select_event_clubs', :to => 'event_clubs#select_event_clubs', :as => 'select_event_clubs', :via => [:get]
      match 'update_event_clubs', :to => 'event_clubs#update_event_clubs', :as => 'update_event_clubs', :via => [:post]
      resource :event_category_registrations do
        member do
          put :update, :as => "update"
        end
      end
      resource :event_categories do
        member do
          put :update, :as => "update"
        end
      end
  end
  
  match 'user/sign_in' => 'user#sign_in'
  match 'user/sign_up' => 'user#sign_up'
  match 'user/create_non_profit_url' => 'user#create_non_profit_url'
  match 'user/delete_non_profit_url' => 'user#delete_non_profit_url'
  # match 'user/create_admin_push_notification' => 'user#create_admin_push_notification'
  # match 'user/delete_admin_push_notification' => 'user#delete_admin_push_notification'
  match '/populate_user_details' => 'user#populate_user_details', :via => [:get]
  match 'self_check_in' => 'events#self_check_in', :via => [:post]
  match 'forgot_password', :to => 'user#forgot_password', :as => 'forgot_password', :via => [:post]
  match 'validate_security_code', :to => 'user#validate_security_code', :as => 'validate_security_code', :via => [:post]
  match 'update_password_details', :to => 'user#update_password_details', :as => 'update_password_details', :via => [:post]
  match 'validate_number', :to => 'user#validate_number', :as => 'validate_number', :via => [:get]
  match 'generate_users_list', :to => 'user#generate_users_list', :as => 'generate_users_list', :via => [:get]
  match 'app_landing_page', :to => 'user#app_landing_page', :as => 'app_landing_page', :via => [:get]
  match '/get_competitor_details' => 'cards#get_competitor_details', :via => [:get]
  match '/my_card_details' => 'cards#my_card_details', :via => [:get]
  # match '/search_cards' => 'cards#search_cards', :via => [:get]
  match '/update_competitor_details' => 'cards#update_competitor_details', :via => [:post]
  match '/categories' => 'home#get_categories'
  match '/charities' => 'home#get_charities'
  match '/get_all_dropdown_values' => 'home#get_all_dropdown_values'
  match 'home' => 'home#index'
  match '/update_judge_code' => 'home#update_judge_code'
  match '/update_profile' => 'profiles#update_profile'
  match '/signup_clubs' => 'home#signup_clubs'
  match '/news' => 'home#news'
  # match '/eventbrite' => 'eventbrite#index'
  # match '/eventbrite/create_registration' => 'eventbrite#create_registration'
  match '/validate_email_on_create_new_user' => 'mobile_checkins#validate_email_on_create_new_user'
  match '/submit_tie_breaker' => 'event_categories#submit_tie_breaker', :via => [:post]
  # match 'motta_sathu', :to => 'events#motta_sathu', :as => 'motta_sathu', :via => [:get]
  # match '/delete_sathu' => 'event_categories#delete_sathu', :via => [:get]
  
  resources :cards
  resources :clubs
  resources :profiles
  resources :events do
    get 'results', :on => :member
    get 'photos', :on => :member
    get 'launch_event', :on => :member
    get 'event_stats', :on => :member
    get 'close_event', :on => :member
    get 'get_non_closed_event_category', :on => :member
    get 'load_more_judge_results_data', :on => :member
    get 'show_season_wise_donations', :on => :collection
  end
  resources :event_categories do
    post 'voting', :on => :member
    get 'announce_event_category_results', :on => :member
    get 'close_event_category', :on => :member
    get 'get_event_category_competitors', :on => :member
    get 'validate_category_name', :on => :member
    get 'force_close_judging_by_mc', :on => :member
    get 'fetch_tied_competitors', :on => :collection
  end

  resources :visitor_votes do
    collection do
      get 'load_visitor_votes'
    end
  end

  resources :judge_votes do
    member do
      get 'get_judges_votes'
    end
  end

  resources :event_fan_voting_results do
    collection do
      get 'track_overall_fan_voting_results'
      get 'track_category_fan_voting_results'
    end
  end

  resources :mobile_checkins do
    get 'event_checkin', :on => :member
    get 'take_photo', :to => 'mobile_checkins#take_photo', :as => 'take_photo'
    get 'search_users', :to => 'mobile_checkins#search_users', :as => 'search_users'
    get 'checkin_users', :to => 'mobile_checkins#checkin_users', :as => 'checkin_users'
    post 'update_checkin_users', :to => 'mobile_checkins#update_checkin_users', :as => 'update_checkin_users'
    post 'remove_checkin_users', :to => 'mobile_checkins#remove_checkin_users', :as => 'remove_checkin_users'
    put 'update_photo', :to => 'mobile_checkins#update_photo', :as => 'update_photo'
    put 'register_comp_to_events', :to => 'mobile_checkins#register_comp_to_events', :as => 'register_comp_to_events'
    get 'edit_checkedin_comp', :to => 'mobile_checkins#edit_checkedin_comp', :as => 'edit_checkedin_comp'
    put 'update_checkedin_comp', :to => 'mobile_checkins#update_checkedin_comp', :as => 'update_checkedin_comp'
    post 'create_new_competitor', :to => 'mobile_checkins#create_new_competitor', :as => 'create_new_competitor'
    delete 'delete_checkedin_comp', :to => 'mobile_checkins#delete_checkedin_comp', :as => 'delete_checkedin_comp'
    get 'delete_checkedin_competitor', :to => 'mobile_checkins#delete_checkedin_competitor', :as => 'delete_checkedin_competitor'
  end

  resources :event_requests do
    # get 'event_checkin', :on => :member    
    # put 'update_checkedin_comp', :to => 'mobile_checkins#update_checkedin_comp', :as => 'update_checkedin_comp'
    # post 'create', :to => 'event_requests#create', :as => 'create'
  end
  
   root :to => 'admin/dashboard#index'

end

app/models/event_request.rb
class EventRequest < ActiveRecord::Base
  # attr_accessible :title, :body
end

app/controllers/event_requests_controller.rb
class EventRequestsController < ApplicationController
	layout "mobile_checkin_layout"

	before_filter :find_event, :only=> [:edit,:update, :show, :destroy]
	before_filter :assign_uuid
	before_filter :check_user_by_uuid #, :only=> [:index]
	before_filter :find_clubs, :only=> [:new,:create,:edit,:update]

	def index
		@events = Event.where(:status=>"Pending", :user_id=>@user.try(:id))
	end

	def new
		@event = Event.new
		@event.build_event_requester_shipping_detail
	end

	def create
		@event = Event.new(params[:event])
		if @event.save
			redirect_to event_requests_path("user[uuid]"=>@uuid)
		else
			@errors = @event.errors.messages
			@shipping_errors = @event.try(:event_requester_shipping_detail).errors.messages
        	find_state(params[:event][:country]) if @errors.present?
        	find_shipping_state(params[:event][:event_requester_shipping_detail_attributes][:shipping_country])  if @shipping_errors.present?
			render "new"
		end
	end

	def edit
		@event.event_requester_shipping_detail
		find_state(@event.try(:country))
		find_shipping_state(@event.try(:event_requester_shipping_detail).try(:shipping_country))
	end

	def update
		if @event.update_attributes(params[:event])
			redirect_to event_requests_path("user[uuid]"=>@uuid)
		else
			@errors = @event.errors.messages
			@shipping_errors = @event.try(:event_requester_shipping_detail).errors.messages
        	find_state(params[:event][:country]) if @errors.present?
        	find_shipping_state(params[:event][:event_requester_shipping_detail_attributes][:shipping_country])  if @shipping_errors.present?
			render "edit"
		end
	end

	def show
		@uuid = params[:user][:uuid] if params[:user].present?
	end

	def destroy
		@event.destroy
		redirect_to event_requests_path("user[uuid]"=>@uuid)
	end

	private

	def find_state(country)
		country_obj = Carmen::Country.named(country)
    	# @states = country_obj.try(:subregions)
    	@states = country_obj.subregions.map do |state| 
			state_code = state.code
		end
    	@state = @event.try(:state)
	end

	def find_shipping_state(country)
		country_obj = Carmen::Country.named(country)
    	# @states = country_obj.try(:subregions)
    	@shipping_states = country_obj.subregions.map do |state| 
			state_code = state.code
		end if country_obj.present?
    	@shipping_state = @event.try(:event_requester_shipping_detail).try(:shipping_state)
	end

	def find_event
		@event = Event.find_by_id(params[:id])
	end

	def assign_uuid
		@uuid = params[:user][:uuid] if params[:user].present?
	end

	def find_clubs
		clubs = Club.order(:name)
		clubs_name = clubs.pluck(:name)
		clubs_id = clubs.pluck(:id)
		@clubs = clubs_name.zip(clubs_id)
	end
end

app/helpers/event_requests_helper.rb
module EventRequestsHelper
end

app/views/event_requests/_form.html.erb
<div class="form-group">
    <%= f.text_field  :requester_mobile, :type=> "number", :class=>"form-control", :placeholder => "Requester's mobile number" %>
    <%if @errors.present? && @errors[:requester_mobile].present?%>
        <p><span style="color:red;"><%=@errors[:requester_mobile].last%></span></p>
    <%end%>
</div>
<div class="form-group">
    <%= f.text_field  :name, :class=>"form-control", :placeholder => "Event Name" %>
    <%if @errors.present? && @errors[:name].present?%>
        <p><span style="color:red;"><%=@errors[:name].last%></span></p>
    <%end%>
</div>
<div class="form-group date-adjust">
    <%= f.text_field  :from_date, :class=>"form-control", :placeholder => "Event Date", :value=>f.object.from_date.present? ? "#{f.object.from_date.to_s(:db)}" : ""%>
    <%=f.select :meridian, options_for_select( ["AM", "PM"], :selected =>f.object.meridian.present? ? f.object.meridian : ""),{:include_blank => false},html_options = {:class => "form-control"} %>
    <%if @errors.present? && @errors[:from_date].present?%>
        <p><span style="color:red;"><%=@errors[:from_date].last%></span></p>
    <%end%>
</div>

<div class="form-group">
    <%= f.text_field  :venue_name, :class=>"form-control", :placeholder => "Venue Name" %>
    <%if @errors.present? && @errors[:venue_name].present?%>
        <p><span style="color:red;"><%=@errors[:venue_name].last%></span></p>
    <%end%>
</div>
<div class="form-group">
    <%= f.text_field  :address_line_1, :class=>"form-control", :placeholder => "Address" %>
    <%if @errors.present? && @errors[:address_line_1].present?%>
        <p><span style="color:red;"><%=@errors[:address_line_1].last%></span></p>
    <%end%>
</div>
<!-- <div class="form-group">
    <%#= f.text_field  :address_line_2, :class=>"form-control", :placeholder => "Address Line 2" %>
    <%#if @errors.present? && @errors[:address_line_2].present?%>
        <p><span style="color:red;"><%#=@errors[:address_line_2].last%></span></p>
    <%#end%>
</div> -->
<div class="form-group">
    <%= f.text_field  :city, :class=>"form-control", :placeholder => "City" %>
    <%= f.hidden_field  :status, :value=> "Pending"%>
    <%if @errors.present? && @errors[:city].present?%>
        <p><span style="color:red;"><%=@errors[:city].last%></span></p>
    <%end%>
</div>
<div class="form-group">    
    <%=f.select :country, options_for_select( Carmen::Country.all.sort, :selected => f.object.country),{:include_blank => "Select Country"},html_options = {:onchange => "getStates($(this).find(':selected').val(),false,'event_request');", :class => "form-control"} %>
    <%if @errors.present? && @errors[:country].present?%>
        <p><span style="color:red;"><%=@errors[:country].last%></span></p>
    <%end%>
</div>
<div class="form-group">
    <%unless f.object.new_record?%>
        <%#country_obj = Carmen::Country.named(f.object.country)
        states = country_obj.subregions
        state = states.coded(f.object.state).try(:name)%>
        <%= f.select  :state, options_for_select(@states, :selected => @state), {:include_blank => "Please select a state"},html_options = {:class => "form-control"} %>
        <%#=f.hidden_field :edit_state, :value=>state%>
    <%else%>
        <%= f.select  :state, options_for_select(@states.present? ? @states : "Please select a state", :selected => @state), {:include_blank => "Please select a state"},html_options = {:class => "form-control"} %>
    <%end%>
    <%if @errors.present? && @errors[:state].present?%>
        <p><span style="color:red;"><%=@errors[:state].last%></span></p>
    <%end%>
</div>
<div class="form-group">
    <%= f.text_field  :no_of_categories, :type=> "number", :class=>"form-control", :placeholder => "Number of Categories" %>
    <%if @errors.present? && @errors[:no_of_categories].present?%>
        <p><span style="color:red;"><%=@errors[:no_of_categories].last%></span></p>
    <%end%>
</div>

<div class="form-group">
    <%=f.select :club_id, options_for_select( @clubs, :selected =>f.object.club_id.present? ? f.object.club_id : "Select a Club"),{:include_blank => "Select a Club"},html_options = {:class => "form-control"} %>
    <%if @errors.present? && @errors[:club_id].present?%>
        <p><span style="color:red;"><%=@errors[:club_id].last%></span></p>
    <%end%>
</div>

<div class="form-group">
    <%= f.text_field  :no_of_judges, :type=> "number", :class=>"form-control", :placeholder => "Number of Judges" %>
    <%if @errors.present? && @errors[:no_of_judges].present?%>
        <p><span style="color:red;"><%=@errors[:no_of_judges].last%></span></p>
    <%end%>
</div>
<div class="form-group">
    <%= f.text_field  :no_of_expected_competitors, :type=> "number", :class=>"form-control", :placeholder => "Number of Expected Competitors" %>
    <%if @errors.present? && @errors[:no_of_expected_competitors].present?%>
        <p><span style="color:red;"><%=@errors[:no_of_expected_competitors].last%></span></p>
    <%end%>
</div>
<div class="form-group">
    <%= f.text_field  :nonprofit_cause, :class=>"form-control", :placeholder => "NonProfit Cause" %>
    <%if @errors.present? && @errors[:nonprofit_cause].present?%>
        <p><span style="color:red;"><%=@errors[:nonprofit_cause].last%></span></p>
    <%end%>
</div>
<div class="form-group">
    <%= f.file_field  :image, :placeholder => "Event Image", :class => "custom-file-input"%>
</div>
<%= f.hidden_field  :user_id, :value=> @user.try(:id)%>

<div style="">
    <h4> Contact Details </h4>
    <%=f.fields_for :event_requester_shipping_detail do |ff|%>
        <div class="form-group">
            <%= ff.text_field  :shipping_contact_name, :class=>"form-control", :placeholder => "Shipping Contact Name" %>
            <%if @shipping_errors.present? && @shipping_errors[:shipping_contact_name].present?%>
                <p><span style="color:red;"><%=@shipping_errors[:shipping_contact_name].last%></span></p>
            <%end%>
        </div>

        <div class="form-group">
            <%= ff.text_field  :shipping_address_line_1, :class=>"form-control", :placeholder => "Shipping Address Line 1" %>
            <%if @shipping_errors.present? && @shipping_errors[:shipping_address_line_1].present?%>
                <p><span style="color:red;"><%=@shipping_errors[:shipping_address_line_1].last%></span></p>
            <%end%>
        </div>

        <div class="form-group">
            <%= ff.text_field  :shipping_address_line_2, :class=>"form-control", :placeholder => "Shipping Address Line 2" %>
            <%if @shipping_errors.present? && @shipping_errors[:shipping_address_line_2].present?%>
                <p><span style="color:red;"><%=@shipping_errors[:shipping_address_line_2].last%></span></p>
            <%end%>
        </div>


        <div class="form-group">
            <%= ff.text_field  :shipping_city, :class=>"form-control", :placeholder => "Shipping City" %>
            <%if @shipping_errors.present? && @shipping_errors[:shipping_city].present?%>
                <p><span style="color:red;"><%=@shipping_errors[:shipping_city].last%></span></p>
            <%end%>
        </div>

        <div class="form-group">    
            <%=ff.select :shipping_country, options_for_select( Carmen::Country.all.sort, :selected => ff.object.shipping_country),{:include_blank => "Select Country"},html_options = {:onchange => "getStates($(this).find(':selected').val(),false,'shipping_event');", :class => "form-control"} %>
            <%if @shipping_errors.present? && @shipping_errors[:shipping_country].present?%>
                <p><span style="color:red;"><%=@shipping_errors[:shipping_country].last%></span></p>
            <%end%>
        </div>
        <div class="form-group">
            <%unless ff.object.new_record?%>
                <%= ff.select  :shipping_state, options_for_select(@shipping_states, :selected => @shipping_state), {:include_blank => "Please select a state"},html_options = {:class => "form-control"} %>
                <%#=f.hidden_field :edit_state, :value=>state%>
            <%else%>
                <%= ff.select  :shipping_state, options_for_select(@shipping_states.present? ? @shipping_states : "Please select a state", :selected => @shipping_state), {:include_blank => "Please select a state"},html_options = {:class => "form-control"} %>
            <%end%>
            <%if @shipping_errors.present? && @shipping_errors[:shipping_state].present?%>
                <p><span style="color:red;"><%=@shipping_errors[:shipping_state].last%></span></p>
            <%end%>
        </div>

        <div class="form-group">
            <%= ff.text_field  :shipping_zip, :class=>"form-control", :placeholder => "Shipping Zip" %>
            <%if @shipping_errors.present? && @shipping_errors[:shipping_zip].present?%>
                <p><span style="color:red;"><%=@shipping_errors[:shipping_zip].last%></span></p>
            <%end%>
        </div>
    <%end%>
</div>

<div class="article-foot-btn form-group">
    <%= f.submit "Submit", class: "btn btn-primary" %>    
    <%= link_to "Cancel", event_requests_path("user[uuid]"=>@uuid), class: "btn btn-primary" %>
</div>

app/views/event_requests/edit.html.erb
<section class="content-section">
    <%class_name = (@event.try(:name).length >= 120) ? "extra-small" : (@event.try(:name).length >= 85) ? "small" : ""%>
    <h2 class="<%=class_name%>"><%=@event.try(:name).try(:capitalize)%></h2>
    <div class="panel">

        <%=form_for @event, :url => { :action => "update", "user[uuid]"=>@uuid }  do |f|  %>
            <article class="article">
                <h4>Edit Request</h4>
                <%=render "form", :f=>f%>
            </article>
        <%end%>

        <!-- </form> -->
    </div>
</section>
<!-- /content-section -->

app/views/event_requests/index.html.erb
<section class="content-section">
    <h2>All Events</h2>
    <div class="panel events-list">
        <article class="article">
            <%= link_to "Request Event", new_event_request_path("user[uuid]"=>@uuid), :class=> "link-btn"%>
            <h4>My Requested events</h4>
            <div class="clearfix"></div>
            <div class="form-group">
                <%if @events.present?%>
                    <%@events.each_with_index do |event,index|%>
                        <div class="manage-event-form">
                            <%=link_to event.name, event_request_path(event.id, "user[uuid]"=>@uuid)%>
                           <div class="form-action">
                                <%=link_to "Edit", edit_event_request_path(event.id, "user[uuid]"=>@uuid)%>
                                <%=link_to "Delete", event_request_path(event, "user[uuid]"=>@uuid),
                                    :confirm => 'Are you sure want to delete?', :method => :delete%>
                           </div>
                        </div>
                    <%end%>
                <%else%>
                    <div style="text-align:center;">No Events Found</div>
                <%end%>
            </div>
        </article>
    </div>
</section>
<!-- /content-section -->

app/views/event_requests/new.html.erb
<section class="content-section">
    <div class="panel">
        <%=form_for @event, :html => {:class => "new_event event_request_form"}, :url => { :action => "create", "user[uuid]"=>@uuid }  do |f|  %>
            <article class="article">
                <h4>Create New Request</h4>
                <%=render "form", :f=>f%>
            </article>
        <%end%>
    </div>
</section>
<!-- /content-section -->

app/views/event_requests/show.html.erb
<section class="content-section">
<%class_name = (@event.try(:name).length >= 120) ? "extra-small" : (@event.try(:name).length >= 85) ? "small" : ""%>
    <h2 class="<%=class_name%>"><%=@event.try(:name).try(:capitalize)%></h2>
    <div class="panel events-list">
        <article class="article">
        <%= link_to "Request Event", new_event_request_path("user[uuid]"=>@uuid), :class=>"link-btn m-r-0"%>
            <h4>Event Details</h4>
        <div class="clearfix"></div>
            <div class="form-group">
                <div class="event-request-detail">
                    <figure>
                        <%if @event.image_file_name.present?%>
                            <%=image_tag ("#{AppConfig.s3_url}/attachments/#{@event.id}/medium/"+@event.image_file_name) %>
                        <%else%>
                            There is no <br/>event image
                        <%end%>
                    </figure>
                    <figcaption>
                        <p><label>Event Name :</label><span><%=@event.try(:name)%></span></p>
                        <p><label>Event Date :</label><span><%=@event.try(:from_date).strftime("%d-%m-%Y %H:%M")%> <%=@event.try(:meridian)%></span></p>
                        <p><label>Address Line1 :</label><span><%=@event.try(:address_line_1)%></span></p>
                        <p><label>Address Line2 :</label><span><%=@event.try(:address_line_2) || "-"%></span></p>
                        <p><label>City :</label><span><%=@event.try(:city)%></span></p>
                        <p><label>Country :</label><span><%=@event.try(:country)%></span></p>
                        <p><label>State :</label><span><%=@event.try(:state)%></span></p>
                        <p><label>Categories :</label><span><%=@event.try(:no_of_categories)%></span></p>
                        <p><label>Event Club :</label><span><%=@event.try(:clubs).try(:first).try(:name)%></span></p>
                        <p><label>Rqstr Name :</label><span><%=@event.try(:user).try(:last_name)%>, <%=@event.try(:user).try(:first_name)%></span></p>
                        <p><label>Rqstr mobile :</label><span><%=@event.try(:requester_mobile)%></span></p>
                    </figcaption>
                </div>
            </div>
        </article>
    </div>
</section>
<!-- /content-section -->